### ISSUE TITLE
DELETE API request not working

### ISSUE THREAD

**Issue by MoeBensu** [DFKI-MLT/TransIns#2]
I recently tried out to use the demo version of `TransIns` and it seems to me that the `DELETE` request isn't working anymore. 

Can this still be fixed or is it done in purpose? 

Anyway, I think, it would be very helpful to have it again, especially if one is working with sensitive datasets (i.e. clinical data). Also, is there more information about the storage of data in case of the demo? Do the translated data get shared or deleted after a period?

Thank you :) 

@jsteffen

**Comment by jsteffen** [comment]
The REST endpoint for requesting the deletion of a document has always been activated, as documented in the README. Please note that a delete function is not available in the web interface.

Currently, we keep the latest 100 submitted documents in the TransIns demonstrator for debugging purposes. Nevertheless, I generally discourage to upload sensitive data to *any* server outside of your environment. One motivation for TransIns was to enable users to translate sensitive documents in their local environment.

**Comment by MoeBensu** [comment]
@jsteffen OK! Then, I misunderstood it, espeically that I've tried [the demo](https://transins.dfki.de/) a while ago and if I'm not mistaken the delete endpoint was working.

Anyways, thank you for the quick answer. I think this closes this issue.
